"""empty message

Revision ID: 7eb237ede24c
Revises: c9625ad02725
Create Date: 2021-07-28 22:59:10.729889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb237ede24c'
down_revision = 'c9625ad02725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('maxtemp', sa.Integer(), nullable=False),
    sa.Column('mintemp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_temp',
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('temp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['temp_id'], ['temp.id'], ondelete='cascade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_temp')
    op.drop_table('temp')
    op.drop_table('photo')
    # ### end Alembic commands ###
