"""empty message

Revision ID: 86b91417f142
Revises: fc035172cf84
Create Date: 2021-07-28 16:21:27.902125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86b91417f142'
down_revision = 'fc035172cf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_temp',
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('temp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['temp_id'], ['temp.id'], ondelete='cascade')
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('temp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name='association_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temp_id'], ['temp.id'], name='association_ibfk_2', ondelete='CASCADE'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('photo_temp')
    # ### end Alembic commands ###
