"""empty message

Revision ID: fc035172cf84
Revises: 5992dfad25e9
Create Date: 2021-07-28 16:20:49.991207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc035172cf84'
down_revision = '5992dfad25e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('temp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['temp_id'], ['temp.id'], ondelete='cascade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
